---
name: apptainer build

on:
    push:
        branches: [master]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        strategy:
            matrix:
                image: [Singularity_MCR.def, Singularity.def]
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
            with:
                fetch-depth: 0
        -   uses: eWaterCycle/setup-apptainer@v2
            with:
                apptainer-version: 1.3.0
        -   name: build sif image
            run: apptainer build cat12.sif ${{ matrix.image }}
