---
name: docker build

on:
    push:
        branches: [main]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
            with:
                fetch-depth: 0
        -   name: Install dependencies
            run: |
                sudo apt-get -y -qq update
                sudo apt-get -y install git-annex
                pip install datalad
        -   name: get test data
            run: make data_ds000001
        -   name: Build the Docker image
            run: |
                make build
                docker images
        -   name: help
            run: docker run --rm cat12 --help
        -   name: quick test
            run: |
                docker run --rm cat12 . . participant view tfce
                docker run --rm cat12 . /foo participant copy tfce
        -   name: segment
            run: make ds000001
